### ISSUE TITLE
Magnetic models at high coefficient range

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/WebClient-Framework#221]
The models displayed have been shown to agree well with what is expected based on the .shc files. When a coefficient higher than what is specified by the model is displayed. The model will still show the highest coefficient value. 

Eg. SIFM has a coefficient range [1,70], when specifying [70,70], one seems to get the same as when specifying [80,100] or even [2000,2000]. 

If a range exceeding the model coefficients is selected I would expect either (1) the range be corrected to reflect what is being shown on the globe (ie [70,70] or [70,-1]) possibly with a notification, or (2) the range specified is displayed, which for a model with no coefficients should display a completely isochromatic model layer on the globe, similar to choosing other invalid ranges like [70,69].

**Comment by santilland** [comment]
We have found the issue in the calculation of the magnetic model, it was taking the last coefficient set even when selecting outside of the range. We need to update the library used for the magnetic model computation and the issue should be solved ( as well as probably the related issue #223 )

**Comment by miktoki** [comment]
Now SIFM of high coefficients displays an isochromatic layer, but the difference CHAOS-6 - SIFM at coefficient ranges above what SIFM can show still does not behave as expected. Is the coefficient range linked to both models?
