### ISSUE TITLE
AV: wrong data line-connections - data gaps

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/WebClient-Framework#323]
The rendering of line connections between data points in AV has following issues:

...

2) In case of a gap between points because of, e.g., missing data or data points being filtered out, non-consecutive points are connected.
![screen-shot-0165](https://user-images.githubusercontent.com/4050019/55877607-c6358c00-5b9a-11e9-8c4b-98e1e8c87972.png)

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/WebClient-Framework/pull/329

**Comment by lmar76** [comment]
In case of data gaps, the issue is still visible. E.g. satellite A, MAG-L data, 01/01/2014-08/01/2014:

![image](https://user-images.githubusercontent.com/20207042/57519716-3eb77600-731c-11e9-823e-e00a013376b9.png)

**Comment by pacesm** [comment]
OK, This case a bit more complicated than the gaps introduced by filtering and we will not be able to resolve it immediately.

I moved it to a new ticket https://github.com/ESA-VirES/WebClient-Framework/issues/333
